### ISSUE TITLE
Error loading app on windows 10

### ISSUE THREAD

**Issue by Kash0321** [mhwlng/fip-elite#12]
Hi

My friend Kerwin has a logitech flight instrumental panel but this week is experimenting an error when app is loading... Pasting image and log with the problem. ¿Can you help us?...

![Imagen de WhatsApp 2023-05-08 a las 19 43 24](https://user-images.githubusercontent.com/10654401/236894286-ec91489e-751e-4b7e-baa1-36297f17840b.jpg)

ERROR 2023-05-08 19:26:29,183 Invoke - AppDispatcherUnhandledException: System.NullReferenceException: Referencia a objeto no establecida como instancia de un objeto.
   en Elite.App.OnExit(ExitEventArgs e)
   en System.Windows.Application.DoShutdown()
   en System.Windows.Application.ShutdownImpl()
   en System.Windows.Application.ShutdownCallback(Object arg)
   en System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   en System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
ERROR 2023-05-08 19:26:29,226 Invoke - AppDispatcherUnhandledException: System.NullReferenceException: Referencia a objeto no establecida como instancia de un objeto.
   en Elite.App.OnExit(ExitEventArgs e)
   en System.Windows.Application.DoShutdown()
   en System.Windows.Application.ShutdownImpl()
   en System.Windows.Application.ShutdownCallback(Object arg)
   en System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   en System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
ERROR 2023-05-08 19:26:29,227 TryCatchWhen - AppDomainUnhandledExceptionHandler: System.NullReferenceException: Referencia a objeto no establecida como instancia de un objeto.
   en Elite.App.OnExit(ExitEventArgs e)
   en System.Windows.Application.DoShutdown()
   en System.Windows.Application.ShutdownImpl()
   en System.Windows.Application.ShutdownCallback(Object arg)
   en System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   en System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   en System.Windows.Threading.DispatcherOperation.InvokeImpl()
   en MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   en System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   en System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   en System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   en MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   en System.Windows.Threading.DispatcherOperation.Invoke()
   en System.Windows.Threading.Dispatcher.ProcessQueue()
   en System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   en MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   en MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   en System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   en System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   en System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   en MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   en MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   en System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   en System.Windows.Application.RunDispatcher(Object ignore)
   en System.Windows.Application.RunInternal(Window window)
   en Elite.App.Main()

**Comment by mhwlng** [comment]
The log doesn't mean anything to me. There are 2 different  log files that you can check.
Did you install the latest version? Older versions don't work anymore.

Maybe a Json file is corrupted? 
You can re-download the latest version, to get the .Json files again.

**Comment by Kash0321** [comment]
Hi again, thanks for your response.

I will paste error from importdatalog.txt

INFO  2023-05-08 19:47:59,362 Main - ImportData started
ERROR 2023-05-08 19:50:26,944 Main - System.Net.WebException: No es posible conectar con el servidor remoto ---> System.Net.Sockets.SocketException: Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder 95.217.226.126:443
   en System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   en System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- Fin del seguimiento de la pila de la excepción interna ---
   en System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   en System.Net.WebClient.DownloadData(Uri address)
   en System.Net.WebClient.DownloadData(String address)
   en ImportData.JsonReaderExtensions.DownloadJson[T](String url, String path, Boolean& wasUpdated)
   en ImportData.Program.Main(String[] args)
INFO  2023-05-08 19:50:26,947 Main - ImportData ended

My friend tell me that he has installed the latest version, and it is just the one that is failing...

Thanks

**Comment by Kash0321** [comment]
Log spanish content translation: An error occurred during the connection attempt as the connected party did not respond properly after a period of time, or an error occurred in the established connection as the connected host has failed to respond 95.217.226.126:443

**Comment by mhwlng** [comment]
A lot of very large files are being loaded in the background.
since the eddb.io website closed, there is now another provider (spansh.co.uk) and the files are MUCH larger than before and take a lot more time to download. This is out of my control to fix.

This software now only works If you have a high speed internet connection and don't stop the program when downloading is not finished yet.

**Comment by Kash0321** [comment]
Thank you very much for your responses, we will try to left it downloading data...

**Comment by mhwlng** [comment]
make sure that when you re-install the last version zip file that you remove all .json files from the data directory first. 
don't just overwrite all the files. 

these are the file sizes at this moment :

![image](https://github.com/mhwlng/fip-elite/assets/1388886/79fff131-eedc-44f9-a22d-0877f8facf22)
(hwinfo.json,blueprints.json,entryData are not part of the update process)

**Comment by Kash0321** [comment]
Hi again, @mhwlng 

Thanks for your advices. My friend has proceeded, several times, to deploy the new version, without success. Finally, what I have done is to download the source code to my PC, build it, and deploy the output. Now it's working, I don't know what the difference could be....
