### ISSUE TITLE
feature request: add tritium details to the mining page

### ISSUE THREAD

**Issue by dwburke** [mhwlng/fip-elite#4]
tritium mining and buying & selling is big all of a sudden... it would be great to have tritium mining and selling information added to the page that currently has panite and LTD information

**Comment by mhwlng** [comment]
the data from here doesnt look so good:
https://eddb.io/commodity/362

I'll look into getting the data from here instead:
https://inara.cz/goods/10269/

**Comment by mhwlng** [comment]
done....
I don't see any mining hotspots on
http://edtools.ddns.net/miner
so I only added buy/sell data

**Comment by dwburke** [comment]
ah, I guess I assumed the mining sites would be on it already, reddit has been really active with people collecting mining data... thanks for looking into it and adding what you have!
