### ISSUE TITLE
Nothing but Elite Logo in Window

### ISSUE THREAD

**Issue by Fenrir200678** [mhwlng/fip-elite#5]
Hi!

I'm trying to get this to work with ED:Odyssey and my Thrustmaster T.16000M HOTAS. I don't have a Logitech Flight Instrument Panel, but am trying to use the window on a second monitor and/or in VR. I installed the  64 bit Logitech Flight Instrument Panel Drivers you mentioned in the README and changed the PID and VID in the joysticksetting.config to get my Thrustmaster recognized. But unfortunately the Toggle Window shows nothing but the Elite Dangerous Logo. Am I missing something?

Log.txt is showing this:

```

INFO  2021-06-12 20:40:02,700 <OnStartup>b__0 - Sending joystick button presses to FIP panel with serial number : window

INFO  2021-06-12 20:40:02,716 AddWindow - Adding new Window device 0 of type: 00000000-0000-0000-0000-000000000000

INFO  2021-06-12 20:40:02,718 InitFipPanelSerialNumber - FipPanel Serial Number : window

INFO  2021-06-12 20:40:02,943 <OnStartup>b__0 - Looking for directinput devices with PID=B10A and VID=044F

INFO  2021-06-12 20:40:02,943 <OnStartup>b__0 - Button numbers : Up=21 Down=23 Left=24 Right=22 Push=25

INFO  2021-06-12 20:40:03,021 <OnStartup>b__0 - PID:b10a - VID:044f - Joystick    - b10a044f-0000-0000-0000-504944564944 - 34dae2f0-b35e-11eb-8001-444553540000 - T.16000M Joystick

INFO  2021-06-12 20:40:03,021 <OnStartup>b__0 - Using Joystick T.16000M Joystick with Instance Guid 34dae2f0-b35e-11eb-8001-444553540000

INFO  2021-06-12 20:40:03,028 <OnStartup>b__0 - PID:b687 - VID:044f - Flight      - b687044f-0000-0000-0000-504944564944 - 34dd53f0-b35e-11eb-8002-444553540000 - TWCS Throttle

INFO  2021-06-12 20:40:03,029 MoveNext - joystick task started

INFO  2021-06-12 20:40:03,828 <OnStartup>b__0 - Fip-Elite started

INFO  2021-06-12 20:40:03,837 MoveNext - json task started

INFO  2021-06-12 20:40:03,839 MoveNext - HWInfo task started

```

Any idea?

Cheers, 
Fenrir

**Comment by mhwlng** [comment]
Your joystick settings are wrong


these are the button numbers of my vkb joystick :
INFO  2021-06-12 20:40:02,943 <OnStartup>b__0 - Button numbers : Up=21 Down=23 Left=24 Right=22 Push=25

you cannot use an 8-way hat switch with the fip software


Please see the whole discussion on the frontier forum

Post in thread 'Information Display for Logitech Flight Instrument Panel' https://forums.frontier.co.uk/threads/information-display-for-logitech-flight-instrument-panel.535231/post-9271469

**Comment by mhwlng** [comment]
P.s. if you don't have a fip panel then you don't need to install the Logitech driver
