### ISSUE TITLE
Setup of fip screens 

### ISSUE THREAD

**Issue by ogmurda** [mhwlng/fip-elite#6]
Hey I’m brand new and I’m ordering 2 fip and a elgato I’m having hard time understanding  how I can setup the saitek fip screens to what you have I’m looking to setup the same way do you have discord or is there way you can help me when my screens come in? Looking to setup elite dangerous the same way you have on the 2 screens

**Comment by mhwlng** [comment]
There is no setup for the fip panels. The installation instructions are on GitHub. I.e install drivers and install software. That's it
